In [126]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

#read in data
df1 = pd.read_csv('data/SPOTRAC.csv')
df1.sort_values(['Year', 'Player'], 
                    axis=0,
					ascending=[True, True],
                    inplace=True)
le = LabelEncoder()
df1["Age_idx"] = le.fit_transform(df1["Age"])
y = df1['Ave Salary']
X = df1['VORP_0']
X_1 = df1['Age']
df1.head(10)

,Player,Pos,Age,Type,FROM,TO,Years,Value,Ave Salary,Max Value,...,Count Records 0,Count Records 1,Count Records 2,VORP_0,VORP_1,VORP_2,MP_0,MP_1,MP_2,Age_idx
0,Alec Burks,SG,29.3,UFA,PHI,NYK,1,6000000,6000000,6000000,...,1,0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,73
1,Alex Len,C,27.4,UFA,SAC,TOR,1,2258000,2258000,2258000,...,1,0,NaN,-0.1,0.0,NaN,NaN,NaN,NaN,54
2,Anthony Davis,C,27.7,UFA,LAL,LAL,5,189903600,37980720,189903600,...,1,1,NaN,-1.0,-0.1,NaN,NaN,NaN,NaN,57
3,Aron Baynes,C,33.9,UFA,PHX,TOR,2,14350000,7175000,14350000,...,1,1,NaN,3.7,3.7,NaN,NaN,NaN,NaN,113
4,Austin Rivers,SG,28.2,UFA,HOU,NYK,3,9975000,3325000,9975000,...,1,0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,62
5,Avery Bradley,PG,29.9,UFA,LAL,MIA,1,5635000,5635000,5635000,...,1,0,NaN,-0.5,0.0,NaN,NaN,NaN,NaN,78
6,Bismack Biyombo,C,28.2,UFA,CHA,CHA,1,3500000,3500000,3500000,...,1,1,NaN,2.4,2.0,NaN,NaN,NaN,NaN,62
7,Bobby Portis,PF,25.8,UFA,NYK,MIL,2,7427150,3713575,7427150,...,1,1,NaN,-0.5,-0.4,NaN,NaN,NaN,NaN,39
8,Bogdan Bogdanovic,SG,28.2,RFA,SAC,ATL,4,72000000,18000000,72000000,...,1,1,NaN,0.2,-0.3,NaN,NaN,NaN,NaN,62
9,Brandon Ingram,SF,23.2,RFA,NOP,NOP,5,158253000,31650600,158253000,...,1,1,NaN,0.7,0.0,NaN,NaN,NaN,NaN,15

In [127]:
df1.dtypes

Player              object
Pos                 object
Age                float64
Type                object
FROM                object
TO                  object
Years                int64
Value                int64
Ave Salary           int64
Max Value            int64
Year                 int64
Year_1               int64
Year _2              int64
Count Records 0      int64
Count Records 1      int64
Count Records 2    float64
VORP_0             float64
VORP_1             float64
VORP_2             float64
MP_0               float64
MP_1               float64
MP_2               float64
Age_idx              int64
dtype: object

In [128]:
X_1

0      29.3
1      27.4
2      27.7
3      33.9
4      28.2
       ...
376    25.2
377    35.7
378    27.5
379    27.8
380    27.2
Name: Age, Length: 381, dtype: float64

In [129]:
df1['Ave Salary']

0       6000000
1       2258000
2      37980720
3       7175000
4       3325000
         ...
376     2271775
377     2905851
378     1637966
379     1968175
380    43031940
Name: Ave Salary, Length: 381, dtype: int64

In [130]:
df1.head(10)

,Player,Pos,Age,Type,FROM,TO,Years,Value,Ave Salary,Max Value,...,Count Records 0,Count Records 1,Count Records 2,VORP_0,VORP_1,VORP_2,MP_0,MP_1,MP_2,Age_idx
0,Alec Burks,SG,29.3,UFA,PHI,NYK,1,6000000,6000000,6000000,...,1,0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,73
1,Alex Len,C,27.4,UFA,SAC,TOR,1,2258000,2258000,2258000,...,1,0,NaN,-0.1,0.0,NaN,NaN,NaN,NaN,54
2,Anthony Davis,C,27.7,UFA,LAL,LAL,5,189903600,37980720,189903600,...,1,1,NaN,-1.0,-0.1,NaN,NaN,NaN,NaN,57
3,Aron Baynes,C,33.9,UFA,PHX,TOR,2,14350000,7175000,14350000,...,1,1,NaN,3.7,3.7,NaN,NaN,NaN,NaN,113
4,Austin Rivers,SG,28.2,UFA,HOU,NYK,3,9975000,3325000,9975000,...,1,0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,62
5,Avery Bradley,PG,29.9,UFA,LAL,MIA,1,5635000,5635000,5635000,...,1,0,NaN,-0.5,0.0,NaN,NaN,NaN,NaN,78
6,Bismack Biyombo,C,28.2,UFA,CHA,CHA,1,3500000,3500000,3500000,...,1,1,NaN,2.4,2.0,NaN,NaN,NaN,NaN,62
7,Bobby Portis,PF,25.8,UFA,NYK,MIL,2,7427150,3713575,7427150,...,1,1,NaN,-0.5,-0.4,NaN,NaN,NaN,NaN,39
8,Bogdan Bogdanovic,SG,28.2,RFA,SAC,ATL,4,72000000,18000000,72000000,...,1,1,NaN,0.2,-0.3,NaN,NaN,NaN,NaN,62
9,Brandon Ingram,SF,23.2,RFA,NOP,NOP,5,158253000,31650600,158253000,...,1,1,NaN,0.7,0.0,NaN,NaN,NaN,NaN,15

In [131]:
df1["Year"]

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
376    2022
377    2022
378    2022
379    2022
380    2022
Name: Year, Length: 381, dtype: int64

In [132]:
# Split the data into training/testing sets
X_train = np.array(X[-259:], A[-259:])
X_test = np.array(X[:-259], A[:-259])

# X_1_train = np.array(X_1[:-25])
# X_1_test = np.array(X_1[-25:])
# Split the targets into training/testing sets
y_train = np.array(Y[-259:])
y_test = np.array(Y[:-259])


#X_train

/var/folders/hw/6bzkhxpn51x7n21dhhj4lc200000gn/T/ipykernel_70107/1227214488.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  X_train = np.array(X[-259:], A[-259:])

TypeError: Field elements must be 2- or 3-tuples, got ''Age''

In [133]:
X_train = X_train[:, np.newaxis]
X_train
X_test = X_test[:, np.newaxis]
X_test
type(X_test)

numpy.ndarray

In [110]:
#plt.scatter(X,Y, color = 'black')
#plt.xlabel('VORP_0')
#plt.ylabel('Salaries')
#plt.xticks(())
#plt.yticks(())
#plt.show()

In [111]:
print(y_train)

[ 1789256 30000000  1669178  2389641  5032750  1789256  1669178  8901378
 10000000  2700000  5000000  2641691  1939350 28333333  1669178  5890000
  1789256  2066635 14520730 11825000  2389641  1921578 14000000 18000000
  1789256  2641691  2641691  2239544  2641691 18250000  3075000  2089448
  1912787  1742428  5155500  1669178 17280000  4000000  3382500  4000000
  5200000  1789256  2401537  1729217  4612500  8200000  5000000  2089448
  2641691  1669178  4374000  1669178 20000000  1742428  4500000  1244388
 25000000  1789256  2160000 12640000  4000000  1669178 44066288  1803969
 12398374 12500000  8947246  5125000  2401537  6667500  1669178 28333334
  2641691  2239544 16867727 20000000  5000000  1789256  1789256  2641691
  4500000  1710908 22680000  3500000  1803969  1489065  2089448  9240000
  3249280 18000000  1620852  2389641  7175000  2641691  6037250  2641691
  2641691  2089448 10012800 10799880  1489065 11630640  5000000  2239544
  6184500  1789256  1714613  1789256  1789256  1789256  2389641 18000000
  2089448  3000000  1803969  8400000  1669178  5032750 10260000  4000000
  1803969  1729217 18750000  1939350  1912787  2389641  5000000  1669178
  2641691  2562500  1669178  2641691  2389641  2641691  1500000  2443581
  7350000  1968175  3666667  3280000  2905851 25000000  1916664  1836090
  2905851  2905851  2905851 12144552  2200000 50203930  1836090  6640975
  2298385  1836090  6802950 11750000  1968175  7840000 17737500  2273291
  2442525  2133278  6640975  4207625  1637966  1984359  2905851 33232282
  8000000  2641682  3280000  1902133  4512000  4612500  1968175  1836090
  1836090  2133278  2463490  1637966  8715000  2905851  2641682  8000000
  2628597  5734280  6876811  2298385 26000000  5043773 34320000  1637966
  1836090  1886069  2169972  6479000  2187500  6640975  2900000  2133278
  1968175  1902133  2298385  1782931 17500000  1984359  1782931  3000000
  7500000  9000000  1637966  6479000  1836090 16500000  2273291  1836090
  9709025 12500000  1637966  2628597  1637966  3500000 15000000 10300000
  2611758  1902133  1902133  1836090  1916664 11277084  8625000  6150000
 11014500  6640975  2463490  1902133  6146342  1836090  2905851  2298385
  2133278  1886069  2905851  1637966  1836090  2628597  2905851  1968175
  2133278  1968185  1902133 14500000  2905851  9100000  2271775  2905851
  1637966  1968175 43031940]

In [112]:
regr = linear_model.LinearRegression()
# Train the model using the training sets
regr.fit(X_train, y_train)

LinearRegression()

In [113]:
# Make predictions using the testing set
y_pred = regr.predict(X_test)
print(y_pred)

[ 5090994.76508868  4889629.13278953  3077338.44209717 12541523.16015728
  5090994.76508868  4084166.60359292  9923769.94026831  4084166.60359292
  5493726.02968698  6500554.19118274  5090994.76508868  4486897.86819123
  4889629.13278953  4889629.13278953  5090994.76508868  4285532.23589208
  5090994.76508868  5090994.76508868  5695091.66198613  4889629.13278953
  5090994.76508868  5493726.02968698  5090994.76508868  5292360.39738783
  4688263.50049038 10326501.20486661  7507382.3526785   7507382.3526785
  4889629.13278953  4889629.13278953  9118307.41107171  4889629.13278953
  6299188.55888359  5090994.76508868  5090994.76508868  5090994.76508868
  5292360.39738783  4688263.50049038  5292360.39738783  5493726.02968698
  7910113.6172768   5695091.66198613  5695091.66198613  6701919.82348189
  5493726.02968698  4486897.86819123  5493726.02968698  6097822.92658444
  4285532.23589208  9319673.04337086  4889629.13278953  5090994.76508868
  6701919.82348189  5090994.76508868  6903285.45578104  8312844.8818751
  7708747.98497765  4889629.13278953  7708747.98497765  5896457.29428529
  9118307.41107171  5090994.76508868  5493726.02968698  5292360.39738783
  5493726.02968698  4889629.13278953  5292360.39738783  5292360.39738783
  4889629.13278953  5090994.76508868  4889629.13278953  4084166.60359292
  5090994.76508868  5090994.76508868  4889629.13278953  5695091.66198613
  5896457.29428529  4688263.50049038  6299188.55888359  5292360.39738783
  5292360.39738783  4889629.13278953  8312844.8818751   6701919.82348189
  8916941.77877256  4889629.13278953  5292360.39738783  4889629.13278953
  5695091.66198613  8715576.1464734   4486897.86819123  5090994.76508868
  5292360.39738783  5090994.76508868  6097822.92658444  5090994.76508868
  5292360.39738783  5292360.39738783  8715576.1464734   4889629.13278953
  7306016.72037935  3882800.97129377  5090994.76508868  4688263.50049038
  6500554.19118274  4889629.13278953  6299188.55888359  4889629.13278953
  4486897.86819123  4688263.50049038  4285532.23589208  5090994.76508868
  7708747.98497765  5090994.76508868  6903285.45578104  4084166.60359292
  7910113.6172768   5695091.66198613  5292360.39738783  4285532.23589208
  3077338.44209717  4486897.86819123]

In [114]:
df1['VORP_0']

0      0.0
1     -0.1
2     -1.0
3      3.7
4      0.0
      ...
376    0.0
377    0.5
378   -0.2
379   -0.1
380    5.4
Name: VORP_0, Length: 381, dtype: float64

In [115]:

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

# Plot outputs
#plt.scatter(X_test, y_test, color="black")
#plt.plot(X_test, y_pred, color="blue", linewidth=3)

#plt.xticks(())
#plt.yticks(())

#plt.show()

Coefficients:
 [2013656.32299151]
Mean squared error: 43219742052013.70
Coefficient of determination: -0.06

In [116]:
from sklearn import linear_model

In [117]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 1.0)

In [118]:
lasso.fit(X_train, y_train)

Lasso()

In [119]:
y_pred = lasso.predict(X_test)

In [120]:
 y_pred

array([ 5090995.42329041,  4889629.95763275,  3077340.76671383,
       12541517.65262375,  5090995.42329041,  4084168.09500212,
        9923766.5990742 ,  4084168.09500212,  5493726.35460573,
        6500553.68289401,  5090995.42329041,  4486899.02631744,
        4889629.95763275,  4889629.95763275,  5090995.42329041,
        4285533.56065978,  5090995.42329041,  5090995.42329041,
        5695091.82026338,  4889629.95763275,  5090995.42329041,
        5493726.35460573,  5090995.42329041,  5292360.88894807,
        4688264.4919751 , 10326497.53038951,  7507381.0111823 ,
        7507381.0111823 ,  4889629.95763275,  4889629.95763275,
        9118304.73644356,  4889629.95763275,  6299188.21723636,
        5090995.42329041,  5090995.42329041,  5090995.42329041,
        5292360.88894807,  4688264.4919751 ,  5292360.88894807,
        5493726.35460573,  7910111.94249762,  5695091.82026338,
        5695091.82026338,  6701919.14855167,  5493726.35460573,
        4486899.02631744,  5493726.35460573,  6097822.7515787 ,
        4285533.56065978,  9319670.20210122,  4889629.95763275,
        5090995.42329041,  6701919.14855167,  5090995.42329041,
        6903284.61420933,  8312842.87381293,  7708746.47683996,
        4889629.95763275,  7708746.47683996,  5896457.28592104,
        9118304.73644356,  5090995.42329041,  5493726.35460573,
        5292360.88894807,  5493726.35460573,  4889629.95763275,
        5292360.88894807,  5292360.88894807,  4889629.95763275,
        5090995.42329041,  4889629.95763275,  4084168.09500212,
        5090995.42329041,  5090995.42329041,  4889629.95763275,
        5695091.82026338,  5896457.28592104,  4688264.4919751 ,
        6299188.21723636,  5292360.88894807,  5292360.88894807,
        4889629.95763275,  8312842.87381293,  6701919.14855167,
        8916939.27078591,  4889629.95763275,  5292360.88894807,
        4889629.95763275,  5695091.82026338,  8715573.80512825,
        4486899.02631744,  5090995.42329041,  5292360.88894807,
        5090995.42329041,  6097822.7515787 ,  5090995.42329041,
        5292360.88894807,  5292360.88894807,  8715573.80512825,
        4889629.95763275,  7306015.54552465,  3882802.62934446,
        5090995.42329041,  4688264.4919751 ,  6500553.68289401,
        4889629.95763275,  6299188.21723636,  4889629.95763275,
        4486899.02631744,  4688264.4919751 ,  4285533.56065978,
        5090995.42329041,  7708746.47683996,  5090995.42329041,
        6903284.61420933,  4084168.09500212,  7910111.94249762,
        5695091.82026338,  5292360.88894807,  4285533.56065978,
        3077340.76671383,  4486899.02631744])

In [121]:
print("Slope: %.2f" % lasso.coef_[0])

Slope: 2013654.66

In [122]:
print("Intercept: %.2f" % lasso.intercept_)

Intercept: 5090995.42

In [123]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

43219738171765.01

In [124]:
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

Coefficient of determination: -0.06